### ISSUE TITLE
Connection refused right after "CONNECTOR CREATED:  FACEBOOK CONNECTOR"

### ISSUE THREAD

**Issue by brasofilo** [dudanogueira/rocket.connect#5]
Oi Duda!
I had this error on the second installation command (docker-compose run). 
I'm running this on a vanilla Ubuntu 20.04 droplet (I'll try on a 18 instance). 

This was the full error:

```
rod@ubuntu-adq:~/rocket$ docker-compose -f local.yml run --rm django python manage.py dev_settings
WARNING: Some services (browser) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Starting mailhog  ... done
Starting postgres ... done
PostgreSQL is available
SERVER CREATED
CONNECTOR CREATED:  {'external_token': 'CONNECTOR_EXTERNAL_TOKEN1', 'endpoint': 'http://waautomate1:8002', 'name': 'WA instance1', 'manager': 'manager1,agent1'}
CONNECTOR CREATED:  {'external_token': 'CONNECTOR_EXTERNAL_TOKEN2', 'endpoint': 'http://waautomate2:8002', 'name': 'WA instance2', 'manager': 'manager2,agent2'}
CONNECTOR CREATED:  FACEBOOK CONNECTOR
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ffab66153d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='rocketchat', port=3000): Max retries exceeded with url: /api/v1/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffab66153d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/app/rocket_connect/instance/management/commands/dev_settings.py", line 218, in handle
    self.handle_rocketchat()
  File "/app/rocket_connect/instance/management/commands/dev_settings.py", line 101, in handle_rocketchat
    rocket = server.get_rocket_client()
  File "/app/rocket_connect/instance/models.py", line 31, in get_rocket_client
    rocket = RocketChat(user, pwd, server_url=self.url)
  File "/usr/local/lib/python3.8/site-packages/rocketchat_API/APISections/base.py", line 36, in __init__
    self.login(user, password)  # skipcq: PTC-W1006
  File "/usr/local/lib/python3.8/site-packages/rocketchat_API/APISections/base.py", line 120, in login
    login_request = requests.post(
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='rocketchat', port=3000): Max retries exceeded with url: /api/v1/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffab66153d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

**Comment by dudanogueira** [comment]
hi! this is probably rocketchat's rate limit.

I never faced this error, but will try changing the order of this command to set the configs first.

Meanwhile, can you turn it off manually?

You need to go to:
Admin > Rate Limiter > and change it to off

let me know if this worked. I will release v0.1.7 later today that fix this.

**Comment by dudanogueira** [comment]
Also, you probably need to wait a little bit after issuing the first command.

can you please try doing like this, without the -d (daemon mode)
docker-compose -f local.yml up

then wait until you are able to access rocketchat, or see that rocketchat is running

open up a second terminal, and run:
docker-compose -f local.yml run --rm django python manage.py dev_settings

**Comment by brasofilo** [comment]
I didn't have the opportunity yet to check your troubleshooting instructions...

Yesterday I run just the first command on an Ubuntu 18. Today when I ran the second command there were memory errors, upgrading the droplet to 2GB RAM made the command without glitches.

As soon as I can, I'll try to finish the installation on the Ubuntu 20 droplet, and probably raise the memory if it fails again. 
Thanks for a lot for the feedback!

**Comment by dudanogueira** [comment]
yes. it  is a memory intensive stack, as it runs postgres, redis, django, rocketchat, mongo, chrome, 2 waautomate instances, celery and some other containers.

Let me know if you need more help.

**Comment by dudanogueira** [comment]
HI! I will close the issue for now. Let me know if you have any other problems running it.

I am developing a cookie cutter to help deploying, as we only have the development mode at the docs for now.

https://github.com/dudanogueira/rocketconnect_cookiecutter
